# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8e71e1fbca0f77c8c9aa06bb0b1c2aff1c34fd87435097b3b93a5306ffe0aabe888f56a11a7968c20b6b15865575452fbdf7e73ac2f23832252cf1d5418d0721

test:
  secret_key_base: b7d02488b63c8c53ebef42175c736176ae48ca5b27b33c7c55466efa484d0433407fd721a0c30473fb987cb22148618a0064d033a92416cdccc796a508e6f404

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
